description = "Telco Churn"

[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "telco-churn"
version = "0.1.0"
requires-python = ">=3.10"

dependencies = [
  "duckdb==1.4.3",
  "huggingface_hub==1.2.3",
  "redis==7.1.0"
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
telco_churn = ["**/*.sql"]

[project.optional-dependencies]
dev = [
  "jupyter",
  "ipykernel",
  "pandas",
]